# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(750, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(750, 440))
        MainWindow.setMaximumSize(QtCore.QSize(750, 440))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Select_label = QtWidgets.QLabel(self.centralwidget)
        self.Select_label.setGeometry(QtCore.QRect(70, 15, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Select_label.setFont(font)
        self.Select_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Select_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Select_label.setObjectName("Select_label")
        self.SelectList = QtWidgets.QListWidget(self.centralwidget)
        self.SelectList.setGeometry(QtCore.QRect(10, 50, 201, 251))
        self.SelectList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SelectList.setObjectName("SelectList")
        self.UniquesCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.UniquesCheck.setGeometry(QtCore.QRect(20, 60, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UniquesCheck.setFont(font)
        self.UniquesCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.UniquesCheck.setObjectName("UniquesCheck")
        self.FragmentsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.FragmentsCheck.setGeometry(QtCore.QRect(20, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FragmentsCheck.setFont(font)
        self.FragmentsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FragmentsCheck.setObjectName("FragmentsCheck")
        self.DivinationCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.DivinationCheck.setGeometry(QtCore.QRect(20, 135, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DivinationCheck.setFont(font)
        self.DivinationCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DivinationCheck.setObjectName("DivinationCheck")
        self.FossilsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.FossilsCheck.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FossilsCheck.setFont(font)
        self.FossilsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FossilsCheck.setObjectName("FossilsCheck")
        self.ScarabsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.ScarabsCheck.setGeometry(QtCore.QRect(20, 210, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScarabsCheck.setFont(font)
        self.ScarabsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ScarabsCheck.setObjectName("ScarabsCheck")
        self.ResonatorsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.ResonatorsCheck.setGeometry(QtCore.QRect(20, 185, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResonatorsCheck.setFont(font)
        self.ResonatorsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ResonatorsCheck.setObjectName("ResonatorsCheck")
        self.IncubatorsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.IncubatorsCheck.setGeometry(QtCore.QRect(20, 260, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IncubatorsCheck.setFont(font)
        self.IncubatorsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.IncubatorsCheck.setObjectName("IncubatorsCheck")
        self.OilsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.OilsCheck.setGeometry(QtCore.QRect(20, 235, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OilsCheck.setFont(font)
        self.OilsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OilsCheck.setObjectName("OilsCheck")
        self.FilterName_label = QtWidgets.QLabel(self.centralwidget)
        self.FilterName_label.setGeometry(QtCore.QRect(230, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.FilterName_label.setFont(font)
        self.FilterName_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FilterName_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FilterName_label.setObjectName("FilterName_label")
        self.League_label = QtWidgets.QLabel(self.centralwidget)
        self.League_label.setGeometry(QtCore.QRect(230, 145, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.League_label.setFont(font)
        self.League_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.League_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.League_label.setObjectName("League_label")
        self.LoadFilter_label = QtWidgets.QLabel(self.centralwidget)
        self.LoadFilter_label.setGeometry(QtCore.QRect(230, 50, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.LoadFilter_label.setFont(font)
        self.LoadFilter_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LoadFilter_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.LoadFilter_label.setObjectName("LoadFilter_label")
        self.SaveFilter_label = QtWidgets.QLabel(self.centralwidget)
        self.SaveFilter_label.setGeometry(QtCore.QRect(230, 250, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.SaveFilter_label.setFont(font)
        self.SaveFilter_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SaveFilter_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SaveFilter_label.setObjectName("SaveFilter_label")
        self.OverrideCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.OverrideCheck.setGeometry(QtCore.QRect(230, 320, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OverrideCheck.setFont(font)
        self.OverrideCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OverrideCheck.setObjectName("OverrideCheck")
        self.LoadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LoadBtn.setGeometry(QtCore.QRect(380, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoadBtn.setFont(font)
        self.LoadBtn.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.LoadBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.LoadBtn.setObjectName("LoadBtn")
        self.SortBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SortBtn.setEnabled(True)
        self.SortBtn.setGeometry(QtCore.QRect(290, 200, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SortBtn.setFont(font)
        self.SortBtn.setMouseTracking(False)
        self.SortBtn.setAutoFillBackground(False)
        self.SortBtn.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.SortBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SortBtn.setCheckable(False)
        self.SortBtn.setAutoDefault(False)
        self.SortBtn.setDefault(False)
        self.SortBtn.setFlat(False)
        self.SortBtn.setObjectName("SortBtn")
        self.SaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveBtn.setGeometry(QtCore.QRect(450, 290, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SaveBtn.setFont(font)
        self.SaveBtn.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.SaveBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SaveBtn.setObjectName("SaveBtn")
        self.Autoupdate_label = QtWidgets.QLabel(self.centralwidget)
        self.Autoupdate_label.setGeometry(QtCore.QRect(230, 350, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Autoupdate_label.setFont(font)
        self.Autoupdate_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Autoupdate_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Autoupdate_label.setObjectName("Autoupdate_label")
        self.Autoupdate = QtWidgets.QComboBox(self.centralwidget)
        self.Autoupdate.setGeometry(QtCore.QRect(230, 380, 241, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Autoupdate.setFont(font)
        self.Autoupdate.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Autoupdate.setObjectName("Autoupdate")
        self.Autoupdate.addItem("")
        self.Autoupdate.addItem("")
        self.Autoupdate.addItem("")
        self.Changes_label = QtWidgets.QLabel(self.centralwidget)
        self.Changes_label.setGeometry(QtCore.QRect(600, 15, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Changes_label.setFont(font)
        self.Changes_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Changes_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Changes_label.setObjectName("Changes_label")
        self.Changes_list = QtWidgets.QListWidget(self.centralwidget)
        self.Changes_list.setGeometry(QtCore.QRect(540, 50, 201, 311))
        self.Changes_list.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Changes_list.setObjectName("Changes_list")
        self.SaveFilterPath = QtWidgets.QTextBrowser(self.centralwidget)
        self.SaveFilterPath.setGeometry(QtCore.QRect(230, 290, 211, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SaveFilterPath.setFont(font)
        self.SaveFilterPath.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SaveFilterPath.setObjectName("SaveFilterPath")
        self.SelectAllBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SelectAllBtn.setGeometry(QtCore.QRect(40, 315, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SelectAllBtn.setFont(font)
        self.SelectAllBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SelectAllBtn.setObjectName("SelectAllBtn")
        self.RemoveAllBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveAllBtn.setGeometry(QtCore.QRect(40, 350, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RemoveAllBtn.setFont(font)
        self.RemoveAllBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.RemoveAllBtn.setObjectName("RemoveAllBtn")
        self.League = QtWidgets.QComboBox(self.centralwidget)
        self.League.setGeometry(QtCore.QRect(310, 150, 171, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.League.setFont(font)
        self.League.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.League.setObjectName("League")
        self.League.addItem("")
        self.League.addItem("")
        self.League.addItem("")
        self.League.addItem("")
        self.FilterName = QtWidgets.QTextBrowser(self.centralwidget)
        self.FilterName.setGeometry(QtCore.QRect(350, 110, 171, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FilterName.setFont(font)
        self.FilterName.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FilterName.setObjectName("FilterName")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(620, 380, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.UniqueMapsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.UniqueMapsCheck.setGeometry(QtCore.QRect(20, 85, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UniqueMapsCheck.setFont(font)
        self.UniqueMapsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.UniqueMapsCheck.setObjectName("UniqueMapsCheck")
        self.SelectList.raise_()
        self.Select_label.raise_()
        self.UniquesCheck.raise_()
        self.FragmentsCheck.raise_()
        self.DivinationCheck.raise_()
        self.FossilsCheck.raise_()
        self.ScarabsCheck.raise_()
        self.ResonatorsCheck.raise_()
        self.IncubatorsCheck.raise_()
        self.OilsCheck.raise_()
        self.FilterName_label.raise_()
        self.League_label.raise_()
        self.LoadFilter_label.raise_()
        self.SaveFilter_label.raise_()
        self.OverrideCheck.raise_()
        self.LoadBtn.raise_()
        self.SortBtn.raise_()
        self.SaveBtn.raise_()
        self.Autoupdate_label.raise_()
        self.Autoupdate.raise_()
        self.Changes_label.raise_()
        self.Changes_list.raise_()
        self.SaveFilterPath.raise_()
        self.SelectAllBtn.raise_()
        self.RemoveAllBtn.raise_()
        self.League.raise_()
        self.FilterName.raise_()
        self.progressBar.raise_()
        self.UniqueMapsCheck.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.Select_label.setBuddy(self.SelectList)
        self.FilterName_label.setBuddy(self.FilterName)
        self.League_label.setBuddy(self.League)
        self.SaveFilter_label.setBuddy(self.SaveFilterPath)
        self.Changes_label.setBuddy(self.Changes_list)

        self.retranslateUi(MainWindow)
        self.RemoveAllBtn.clicked.connect(self.UniquesCheck.toggle)
        self.RemoveAllBtn.clicked.connect(self.UniqueMapsCheck.toggle)
        self.RemoveAllBtn.clicked.connect(self.FragmentsCheck.toggle)
        self.RemoveAllBtn.clicked.connect(self.DivinationCheck.toggle)
        self.RemoveAllBtn.clicked.connect(self.FossilsCheck.toggle)
        self.RemoveAllBtn.clicked.connect(self.ResonatorsCheck.toggle)
        self.RemoveAllBtn.clicked.connect(self.ScarabsCheck.toggle)
        self.RemoveAllBtn.clicked.connect(self.OilsCheck.toggle)
        self.RemoveAllBtn.clicked.connect(self.IncubatorsCheck.toggle)
        self.SortBtn.clicked.connect(self.progressBar.reset)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.FilterName, self.League)
        MainWindow.setTabOrder(self.League, self.LoadBtn)
        MainWindow.setTabOrder(self.LoadBtn, self.SortBtn)
        MainWindow.setTabOrder(self.SortBtn, self.SaveFilterPath)
        MainWindow.setTabOrder(self.SaveFilterPath, self.SaveBtn)
        MainWindow.setTabOrder(self.SaveBtn, self.OverrideCheck)
        MainWindow.setTabOrder(self.OverrideCheck, self.Autoupdate)
        MainWindow.setTabOrder(self.Autoupdate, self.SelectList)
        MainWindow.setTabOrder(self.SelectList, self.UniquesCheck)
        MainWindow.setTabOrder(self.UniquesCheck, self.UniqueMapsCheck)
        MainWindow.setTabOrder(self.UniqueMapsCheck, self.FragmentsCheck)
        MainWindow.setTabOrder(self.FragmentsCheck, self.DivinationCheck)
        MainWindow.setTabOrder(self.DivinationCheck, self.FossilsCheck)
        MainWindow.setTabOrder(self.FossilsCheck, self.ResonatorsCheck)
        MainWindow.setTabOrder(self.ResonatorsCheck, self.ScarabsCheck)
        MainWindow.setTabOrder(self.ScarabsCheck, self.OilsCheck)
        MainWindow.setTabOrder(self.OilsCheck, self.IncubatorsCheck)
        MainWindow.setTabOrder(self.IncubatorsCheck, self.SelectAllBtn)
        MainWindow.setTabOrder(self.SelectAllBtn, self.RemoveAllBtn)
        MainWindow.setTabOrder(self.RemoveAllBtn, self.Changes_list)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Select_label.setText(_translate("MainWindow", "Select"))
        self.UniquesCheck.setText(_translate("MainWindow", "Uniques"))
        self.FragmentsCheck.setText(_translate("MainWindow", "Fragments"))
        self.DivinationCheck.setText(_translate("MainWindow", "Divination Cards"))
        self.FossilsCheck.setText(_translate("MainWindow", "Fossils"))
        self.ScarabsCheck.setText(_translate("MainWindow", "Scarabs"))
        self.ResonatorsCheck.setText(_translate("MainWindow", "Resonators"))
        self.IncubatorsCheck.setText(_translate("MainWindow", "Incubators"))
        self.OilsCheck.setText(_translate("MainWindow", "Oils"))
        self.FilterName_label.setText(_translate("MainWindow", "Filter Name:"))
        self.League_label.setText(_translate("MainWindow", "League:"))
        self.LoadFilter_label.setText(_translate("MainWindow", "Load .filter file"))
        self.SaveFilter_label.setText(_translate("MainWindow", "Save .filter file"))
        self.OverrideCheck.setText(_translate("MainWindow", "Override .filter file"))
        self.LoadBtn.setText(_translate("MainWindow", "Load"))
        self.SortBtn.setText(_translate("MainWindow", "Sort Items"))
        self.SaveBtn.setText(_translate("MainWindow", "Save"))
        self.Autoupdate_label.setText(_translate("MainWindow", "Autoupdate"))
        self.Autoupdate.setItemText(0, _translate("MainWindow", "None"))
        self.Autoupdate.setItemText(1, _translate("MainWindow", "When PC starts"))
        self.Autoupdate.setItemText(2, _translate("MainWindow", "Every hour"))
        self.Changes_label.setText(_translate("MainWindow", "Changes"))
        self.SelectAllBtn.setText(_translate("MainWindow", "Select All"))
        self.RemoveAllBtn.setText(_translate("MainWindow", "Remove All"))
        self.League.setItemText(0, _translate("MainWindow", "Current League SC"))
        self.League.setItemText(1, _translate("MainWindow", "Current League HC"))
        self.League.setItemText(2, _translate("MainWindow", "Standart SC"))
        self.League.setItemText(3, _translate("MainWindow", "Standart HC"))
        self.FilterName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.UniqueMapsCheck.setText(_translate("MainWindow", "Unique Maps"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
